#!/bin/bash
#-----------------------------------------------------------------------------
# The MIT License
#
# Copyright (c) 2012 Rick Beton <rick@bigbeeconsultants.co.uk>
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE.
#-----------------------------------------------------------------------------

if [ $UID -ne 0 ]; then

  echo Increasing privileges...
  sudo $0 $*

else

  SUPPORTED="apache2 cherokee lighttpd nginx"
  NOTFOUND=1

  for s in $SUPPORTED; do
    if [ -x /etc/init.d/$s ]; then
      /etc/init.d/$s stop
    fi
  done

  for s in $SUPPORTED; do
    if [ "$1" = "$s" ]; then
      if [ -x /etc/init.d/$s ]; then
        sleep 1
        /etc/init.d/$s start
      fi
      NOTFOUND=0
    fi
  done

  if [ $NOTFOUND -gt 0 ]; then
    echo Usage: $0 server
    echo Currently supported servers are: apache2 cherokee nginx
  fi

fi
